stages:
    - test
    - build
    - deploy

test_redoc:
    stage: test
    image: daedalusproject/base_node12:202004061805
    script:
        - npm install
        - npm test

build_api_docs:
    stage: build
    image: daedalusproject/base_node12:202004061805
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
        - web_deploy
        expire_in: 5 minutes

deploy_develop_image:
    stage: deploy
    image: daedalusproject/base_docker:202004061805
    script:
        - IMAGENAME=daedalus-core-docs-develop
        - RELEASEDATE=$(date)
        - docker build --network=host --no-cache -t "${IMAGENAME}" -f containers/develop/Dockerfile .
        - docker login --username "${DOCKERHUBUSER}" --password "${DOCKERHUBPASSWORD}"
        - docker create --name="${IMAGENAME}" -i "${IMAGENAME}"
        - docker commit -m "$RELEASEDATE" -a "Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>" "${IMAGENAME}" daedalusproject/"${IMAGENAME}"
        - docker push daedalusproject/"${IMAGENAME}"
        - docker stop "${IMAGENAME}"
        - docker rm "${IMAGENAME}"
        - docker rmi "${IMAGENAME}"
    dependencies:
    - build_api_docs
    only:
    - /^develop$/

deploy_release_image:
    stage: deploy
    image: daedalusproject/base_docker:202004061805
    script:
        - IMAGENAME=daedalus-core-docs
        - RELEASEDATE=$(date)
        - docker build --network=host --no-cache -t "${IMAGENAME}" -f containers/develop/Dockerfile .
        - docker login --username "${DOCKERHUBUSER}" --password "${DOCKERHUBPASSWORD}"
        - docker create --name="${IMAGENAME}" -i "${IMAGENAME}"
        - docker tag "${IMAGENAME}" daedalusproject/"${IMAGENAME}":"${CI_COMMIT_REF_NAME}"
        - docker tag "${IMAGENAME}" daedalusproject/"${IMAGENAME}":latest
        - docker commit -m "$RELEASEDATE" -a "Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>" "${IMAGENAME}" daedalusproject/"${IMAGENAME}"
        - docker push daedalusproject/"${IMAGENAME}":"${CI_COMMIT_REF_NAME}"
        - docker push daedalusproject/"${IMAGENAME}":latest
        - docker stop "${IMAGENAME}"
        - docker rm "${IMAGENAME}"
        - docker rmi "${IMAGENAME}"
    dependencies:
    - build_api_docs
    only:
    - /^v-.*$/
