openapi: "3.0.0"
info:
  version: 0.0.1
  title: Daedalus-Core
  contact:
    email: acastellano@daedalus-project.io
    url: 'https://daedalus-project.io/contact'
  license:
    name: GNU General Public License 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
  description: |
    Daedalus Poject Core API specification.

    # Introduction

    This specification is intended to to be a good starting point for describing
    this API, offering developers examples for working with it.

externalDocs:
  description: Daedalus Project Docs
  url: 'https://readthedocs.org'

tags:
  - name: Organization
  - name: User

servers:
  - url: 'https://api-dev.daedalus-project.io'
